name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate App Icons
        run: npx @capacitor/assets generate --android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Generate Keystore & Print SHA-1 (MAGIC KEY)
        run: |
          keytool -genkey -v -keystore $GITHUB_WORKSPACE/gh-actions.keystore -alias mykey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
          echo "========================================="
          echo "FIREBASE KE LIYE SHA-1 CHABI YAHAN HAI:"
          keytool -list -v -keystore $GITHUB_WORKSPACE/gh-actions.keystore -alias mykey -storepass android | grep SHA1
          echo "========================================="

      - name: Build & Force Sign APK
        working-directory: android
        run: ./gradlew assembleDebug -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/gh-actions.keystore -Pandroid.injected.signing.store.password=android -Pandroid.injected.signing.key.alias=mykey -Pandroid.injected.signing.key.password=android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
